#!/bin/sh
#
# author: Edvard Majakari (EdvardM)
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

# Redirect output to stderr.
exec 1>&2

PATTERN="<<<<"

if grep -q $PATTERN **/*.tex; then
	echo "Has conflict markers"
	exit 1
fi

